rarbgapi: fix for Python3
verybada/rarbgapi pull request #3
Opened 2017-08-10 20:47 UTC by easybe

2017-08-11 14:31 UTC, verybada submitted a review, later dismissed

2017-08-11 15:06 UTC, verybada requested changes
Thanks for you help but I got some idea about changes

2017-08-11 15:06 UTC, verybada commented on rarbgapi/rarbgapi.py
How about correct the key here and do it for format_ only?
```
if key == 'format_':
    key = 'format'
```
Because it is not necessary update key if value is None

2017-08-11 15:06 UTC, verybada commented on rarbgapi/rarbgapi.py
> +            except KeyError:
Do you fix the problem that server returns `{"error":"No results found","error_code":20}` if nothing found?
If yes, how about raise a notfound exception in json_hook and functions should take care this by themselves. The request decorator is used to retry for network/expire error and just return an empty list if keyerror raising is too implicit.

2017-08-11 22:50 UTC, easybe commented on rarbgapi/rarbgapi.py
> +            except KeyError:
No, I get:

    Unexpected exceptin 'torrent_results'
    Traceback (most recent call last):
      File "/Users/easyb/Documents/src/rarbgapi/rarbgapi/rarbgapi.py", line 130, in wrapper
        return json_['torrent_results']
    KeyError: 'torrent_results'

2017-08-11 23:24 UTC, easybe commented on rarbgapi/rarbgapi.py
> +            except KeyError:
Yes, but still I would like to receive an empty list if nothing was found. Do you not like that?

2017-08-13 02:57 UTC, verybada commented
Yes, sure.  Thanks for your help, I'll merge the request.

2017-08-12 7:24 GMT+08:00 Ezra Bühler <notifications@github.com>:

> *@easybe* commented on this pull request.
> ------------------------------
>
> In rarbgapi/rarbgapi.py
> <https://github.com/verybada/rarbgapi/pull/3#discussion_r132800477>:
>
> > @@ -127,6 +127,8 @@ def wrapper(self, *args, **kwargs):
>                  resp = func(self, token=self._token, *args, **kwargs)
>                  json_ = resp.json(object_hook=json_hook)
>                  return json_['torrent_results']
> +            except KeyError:
>
> Yes, but still I would like to receive an empty list if nothing was found.
> Do you not like that?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/verybada/rarbgapi/pull/3#discussion_r132800477>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAhfGPcqTZqYCnGy1qKpQawQ2tah5ML_ks5sXOKbgaJpZM4Oz9X->
> .
>

2017-08-13 02:58 UTC, merged